name: Update Sponsors

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'sponsorkit/sponsors.json'

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 20

      - name: Generate sponsors SVG
        run: node scripts/generate-sponsors.cjs
        env:
          GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          AFDIAN_USER_ID: ${{ secrets.AFDIAN_USER_ID }}
          AFDIAN_TOKEN: ${{ secrets.AFDIAN_TOKEN }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: 'chore: update sponsors.svg'
          file_pattern: 'docs/public/assets/sponsors.*'
